[env:esp32s3]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200

; Librerías necesarias para la cámara
lib_deps =
    esp32-camera

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; Esto hace que el Serial use el puerto USB nativo
    -D CORE_DEBUG_LEVEL=5